name: python-linters

on: [ push, pull_request ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: 120
