name: markdown-linter

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.md"
      - ".github/workflows/markdown_lint.yaml"
      - "markdown-rules.rb"
permissions:
  contents: read
jobs:
  markdown-lint:
    name: Lint repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install mdl
        run: gem install mdl
      - name: Run markdown-linter
        run: mdl -s ./markdown-rules.rb .
