name: markdown-linter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdown_lint.yaml"
permissions:
  contents: read
jobs:
  markdownlint:
    name: Lint repository
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: "**/*.md"
          config_file: .markdownlint.yaml
          rules: examples/rules/custom.js

